Add request info get user details
BIBSYSDEV/nva-commons pull request #103
Opened 2020-09-24 22:33 UTC by axthosarouris

2020-09-25 06:24 UTC, norrs reviewed
Just a glimt by this, :+1: for doing this but I want to wait with merging this until we have made the new releases that we want to roll out for sandbox, and test today.

2020-09-26 08:15 UTC, brinxmat requested changes
Missing Javadoc caught by Codacy, otherwise 👍

2020-09-29 12:05 UTC, norrs requested changes
Nits, and question that @svenngjeto should follow up.

2020-09-29 12:05 UTC, norrs commented on src/test/java/nva/commons/handlers/RequestInfoTest.java
> +    private void updateRequestContext(RequestInfo requestInfo, String expectedCustomerId, JsonPointer customerId) {
would it be more clear to use:

Find it odd to pass reference to the object `requestInfo` and then it gets modified inside a function. 

So reading: 
```
  RequestInfo requestInfo = new RequestInfo();

        String expectedUsername = "orestis";
        updateRequestContext(requestInfo, expectedUsername, RequestInfo.FEIDE_ID);
```

feels weird. 

Thinking more:

```
  RequestInfo requestInfo = new RequestInfo();
  requestInfo.setRequestContext(createNestedNodesFromJsonPointer(RequestInfo.CUSTOMER_ID, valueOfCustomerId))

  assertThat(requestInfo.getCustomerId().orElseThrow(), is(equalTo(expectedCustomerId)))
```

2020-09-29 12:31 UTC, svenngjeto commented on src/main/java/nva/commons/handlers/RequestInfo.java
> +    public Optional<String> getUsername() {
If it is an existing user we can use userName which in cognito context is something like 'FeideIdentityProvider_29f2fab2......', otherwise we have to lookup the user via feideid when working with cognito. In 'UsersAndRoles' table username = feideid

2020-09-29 12:38 UTC, axthosarouris commented on src/main/java/nva/commons/handlers/RequestInfo.java
> +    public Optional<String> getUsername() {
@norrs I do not think that this should actually be the case. The cognito username will be irrelevant if we change the cognito instance.  We would like something that will survive a possible regeneration of cognito. It could be an ID that comes from BARE but this is an open discussion at the moment.

2020-09-29 12:47 UTC, axthosarouris commented on src/test/java/nva/commons/handlers/RequestInfoTest.java
> +    private void updateRequestContext(RequestInfo requestInfo, String expectedCustomerId, JsonPointer customerId) {
fixed :)

2020-09-29 12:48 UTC, norrs commented on src/main/java/nva/commons/handlers/RequestInfo.java
> +    public Optional<String> getUsername() {
So here my train of thought @axthosarouris : 

When I'm thinking of a username in the context of `RequestInfo` , it is something that is populated by our IdP, in this case which is the cognito username. 

Maybe rename it to be `getFeideUsername()` then to avoid confusion?

2020-09-29 12:54 UTC, norrs approved these changes
Sexy. LGTM.

2020-09-29 13:46 UTC, brinxmat approved these changes

2020-09-30 07:37 UTC, merged