Now only running on main and master branch
BIBSYSDEV/nva-commons pull request #151
Opened 2021-01-26 14:23 UTC by janbj

2021-01-26 15:05 UTC, axthosarouris approved these changes

2021-01-26 15:54 UTC, brinxmat approved these changes

2021-01-26 16:42 UTC, axthosarouris requested changes
Should this be directed to main branch?

2021-01-27 09:21 UTC, janbj commented
> Should this be directed to main branch?

Will merge to main later.

2021-01-27 09:39 UTC, merged