Created commons dynamodb module with ItemMapper
BIBSYSDEV/nva-commons pull request #159
Opened 2021-02-05 13:27 UTC by janbj

2021-02-05 13:28 UTC, janbj commented on dynamodb/build.gradle
> +
I will take a check for exclusions here

2021-02-05 13:30 UTC, brinxmat approved these changes

2021-02-05 14:55 UTC, axthosarouris commented on dynamodb/src/main/java/nva/commons/dynamodb/ItemMapper.java
> +        var jsonNode = objectMapper.convertValue(item.toJSON(), JsonNode.class);
This converts the String produced by the "toJson()" to a StringNode. The result here is a StringnNode. The final result will be 
```
" {\"id\":\"value\"}" instead of a real json string.
```

2021-02-05 14:57 UTC, axthosarouris commented on dynamodb/src/test/java/nva/commons/dynamodb/ItemMapperTest.java
> +        assertThat(json, is(notNullValue()));
The json string is not a Json string. Maybe we should create a small Dynamo Json file and the expected Json and compare them. Now we do not know if we are losing any information. 
Better would be if we used DynamoDb local to insert an object and read it again using our (de)/serializer. Then we would know it works.

2021-02-05 15:07 UTC, axthosarouris requested changes
Requested changes: the above comments.

General comment: We need a local database for our tests. Without it I do not think we can migrate to sdk2. It seems that there are two alternatives (listed below).  Do we consider the usage of a new local dynamodb to be part of this task?


* https://hub.docker.com/r/amazon/dynamodb-local/
* https://github.com/aws/aws-sdk-java-v2/blob/93269d4c0416d0f72e086774265847d6af0d54ec/services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/extensions/dynamodb/mappingclient/functionaltests/LocalDynamoDb.java

2021-02-05 15:08 UTC, axthosarouris commented
Do we have both develop and main? Should we protect develop ?

2021-02-08 07:44 UTC, janbj commented on dynamodb/src/main/java/nva/commons/dynamodb/ItemMapper.java
> +        var jsonNode = objectMapper.convertValue(item.toJSON(), JsonNode.class);
Hm,  had a reason for this originally as a part of trying to read to a v2 Map<String,AttributeValue> but you are of course right.

2021-02-08 13:54 UTC, brinxmat submitted a review, later dismissed

2021-02-08 14:47 UTC, axthosarouris commented on build.gradle
> +    version = '1.0.2'
Why to merge in develop? Version number is 1.0.3

2021-02-08 14:47 UTC, axthosarouris approved these changes

2021-02-08 14:48 UTC, axthosarouris requested changes
wrong branch?

2021-02-09 08:14 UTC, axthosarouris approved these changes

2021-02-09 08:16 UTC, merged