Checking Accept header for supported media types
BIBSYSDEV/nva-commons pull request #250
Opened 2021-09-15 08:51 UTC by janbj

2021-09-15 11:54 UTC, axthosarouris requested changes
The following method should be added to the RequestAuthorizer class.
```
  @Override
    protected void checkHeaders(RequestInfo requestInfo)  {
        //do nothing;
    }
```

2021-09-15 11:54 UTC, axthosarouris commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +    public void handleRequestShouldReturnUnsupportedMediaType() throws IOException {
when should it return UnsupportedMediaType?

2021-09-15 11:54 UTC, axthosarouris commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +    @DisplayName("handleRequest should return UnsupportedMediaType")
remove display names. no reason to keep in sync two things. If you see any, it is once we thought it was a good idea

2021-09-15 11:54 UTC, axthosarouris commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +        Map<String,String> headers = new ConcurrentHashMap<>();
unsupportedHeaders

2021-09-15 11:54 UTC, axthosarouris commented on build.gradle
> +    version = '1.9.1'
I think the change is a breaking change. I would suggest 1.10.0

2021-09-15 11:54 UTC, axthosarouris commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +
I think we should have a test about wildcards and the supported values. A parametrized test could be enough

2021-09-15 11:54 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RestRequestHandler.java
> +            suppliedAcceptsHeadersAreSupported(requestInfo, listSupportedHeaders());
why is passing a method call as parameter necessary? You can call the private method directly

2021-09-15 11:54 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RestRequestHandler.java
> +    public static final List<String> DEFAULT_SUPPORTED_HEADERS = List.of(APPLICATION_JSON, WILDCARD);
Should we add APPLICATION_JSON_LD?

2021-09-15 11:54 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RestRequestHandler.java
> +    protected String getDefaultResponseHeader() {
defaultHeaders in ApiGatewayHandler should be updated

2021-09-16 13:59 UTC, axthosarouris requested changes

2021-09-16 13:59 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RestRequestHandler.java
> +                        .findAny().isPresent())
Suggestion:
```

    private void suppliedAcceptsHeadersAreSupported(List<MediaType> acceptMediaTypes)
            throws UnsupportedAcceptHeaderException {
        acceptMediaTypes.stream()
                .filter(this::somethingIsHappeningHere)
                .findAny()
                .orElseThrow(UnsupportedAcceptHeaderException::new);
    }

    private boolean somethingIsHappeningHere(MediaType outer) {
        return listSupportedHeaders().stream().anyMatch(inner -> inner.is(outer));
    }
```

2021-09-17 07:27 UTC, axthosarouris requested changes

2021-09-17 07:27 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RestRequestHandler.java
> +                .findAny().isPresent();
replace with anyMatch()

2021-09-17 08:00 UTC, brinxmat requested changes

2021-09-17 08:00 UTC, brinxmat commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +        GatewayResponse<String> response = GatewayResponse.fromOutputStream(outputStream);
Extract?

2021-09-17 08:37 UTC, axthosarouris approved these changes

2021-09-20 08:07 UTC, axthosarouris requested changes

2021-09-20 08:07 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/ContentTypes.java
> -    public static final String APPLICATION_JSON_LD = "application/ld+json".toLowerCase(Locale.ROOT);
I think json-ld content type should stay.

2021-09-20 08:20 UTC, brinxmat submitted a review, later dismissed

2021-09-20 09:04 UTC, axthosarouris requested changes

2021-09-20 09:30 UTC, axthosarouris approved these changes

2021-09-20 09:30 UTC, merged