moving dependencies to libs.versions.toml
BIBSYSDEV/nva-commons pull request #277
Opened 2021-11-18 11:48 UTC by axthosarouris

2021-11-29 18:36 UTC, brinxmat requested changes

2021-11-29 18:36 UTC, brinxmat commented on apigateway/build.gradle
> +   implementation libs.guava
Add one space

2021-11-29 18:36 UTC, brinxmat commented on core/build.gradle
> +    implementation  libs.zalando
remove one space

2021-11-30 07:53 UTC, svenngjeto approved these changes

2021-12-02 09:52 UTC, merged