Added support for multiple objectmappers for different mediatypes
BIBSYSDEV/nva-commons pull request #324
Opened 2022-02-21 08:45 UTC by janbj

2022-02-21 09:00 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/ApiGatewayHandler.java
> +    public ObjectMapper getObjectMapper(RequestInfo requestInfo) throws UnsupportedAcceptHeaderException {
Do we have an example for this use case?  The included test uses the default objectMapper and not one of the Map of the mediaTypes to objectMapper.

2022-02-21 09:08 UTC, axthosarouris commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +    void handlerSendsRawJsonWhenUsingPassthroughObjectMapper() throws Exception {
Can't this be solved by the handler returning JsonNode?  i.e. 

```
public RawJsonResponseHandler(){


public JsonNode processInput(){

 return Try.attempt(() -> JsonUtils.dtoObjectMapper.writeValueAsString(body))
                   .map(bodyString->JsonUtils.dtoObjectMapper.readTree(bodyString)).orElseThrow();
}

}

2022-02-21 09:08 UTC, axthosarouris commented on buildSrc/src/main/groovy/nvacommons.java-conventions.gradle
> +version = '1.20.13-beta4'
Just put 1.20.14. I have created a new package apigatewayv2 that is not ready yet, but I do not think it is such a problem.

2022-02-21 09:39 UTC, janbj commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +    void handlerSendsRawJsonWhenUsingPassthroughObjectMapper() throws Exception {
We want to support XML in the response.

2022-02-21 09:40 UTC, janbj commented on apigateway/src/main/java/nva/commons/apigateway/ApiGatewayHandler.java
> +    public ObjectMapper getObjectMapper(RequestInfo requestInfo) throws UnsupportedAcceptHeaderException {
I will create a test for this.

2022-02-22 09:44 UTC, axthosarouris requested changes

2022-02-22 09:44 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/GatewayResponse.java
> +    public static <T> GatewayResponse<T> fromOutputStream(ByteArrayOutputStream outputStream, Class<T> className)
Do not break the API. Keep the old the methods but deprecate them.

```
  * Create GatewayResponse object from an output stream. Used when we call the method {@code handleRequest()} of a
     * Handler directly and we want to read the output.
     *
     * @param outputStream the outputStream updated by the lambda handler
     * @return the GatewayResponse containing the output of the handler
     * @throws JsonProcessingException when the OutputStream cannot be parsed to a JSON object.
     */
    public static <T> GatewayResponse<T> fromOutputStream(ByteArrayOutputStream outputStream, Class<T> className)
        throws JsonProcessingException {
        String json = outputStream.toString(StandardCharsets.UTF_8);
        return fromString(json, className);
    }

    @Deprecated(forRemoval = true)
    public static <T> GatewayResponse<T> fromOutputStream(ByteArrayOutputStream outputStream)
        throws JsonProcessingException {
        String json = outputStream.toString(StandardCharsets.UTF_8);
        return fromString(json);
    }

    /**
     * Create GatewayResponse object from a String. Used when we call the method {@code handleRequest()} of a Handler
     * directly and we want to read the output. Usually the String is the output of an OutputStream.
     *
     * @param responseString a String containing the serialized GatwayResponse
     * @return the GatewayResponse containing the output of the handler
     * @throws JsonProcessingException when the OutputStream cannot be parsed to a JSON object.
     */
    public static <T> GatewayResponse<T> fromString(String responseString, Class<T> className)
        throws JsonProcessingException {
        if (responseBodyIsString(className)) {
            return constructGatewayResponseWithStringBody(responseString);
        } else {
            return constructResponseWithJsonObjectBody(responseString);
        }
    }

    @Deprecated(forRemoval = true)
    public static <T> GatewayResponse<T> fromString(String responseString)
        throws JsonProcessingException {
        return constructResponseWithJsonObjectBody(responseString);
    }

    private static <T> boolean responseBodyIsString(Class<T> className) {
        return className.getTypeName().equals(String.class.getTypeName());
    }

    private static <T> GatewayResponse<T> constructResponseWithJsonObjectBody(String responseString)
        throws JsonProcessingException {
        TypeReference<GatewayResponse<T>> typeref = new TypeReference<>() {
        };
        return defaultRestObjectMapper.readValue(responseString, typeref);
    }

    private static <T> GatewayResponse<T> constructGatewayResponseWithStringBody(String responseString)
        throws JsonProcessingException {
        JsonNode jsonNode = defaultRestObjectMapper.readTree(responseString);
        String body = jsonNode.get("body").asText();
        TypeReference<Map<String, String>> typeref = new TypeReference<>() {
        };
        Map<String, String> headers = defaultRestObjectMapper.convertValue(jsonNode.get("headers"), typeref);
        int statusCode = jsonNode.get("statusCode").asInt();
        return (GatewayResponse<T>)
                   attempt(() -> new GatewayResponse(body, headers, statusCode, defaultRestObjectMapper)).orElseThrow();
    }
```

2022-02-22 09:44 UTC, axthosarouris commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +    void handlerRespondsWithJsonWhenClientAsksForJson() throws Exception {
shouldRetrurnJsonObjectWhenClientAsksForJson

2022-02-22 09:44 UTC, axthosarouris commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +    void handlerRespondsWithXmlBodyWhenClientAsksForXml() throws Exception {
ditto

2022-02-22 09:44 UTC, axthosarouris commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +        var objectMapper = dtoObjectMapper;
unusled line

2022-02-22 09:44 UTC, axthosarouris commented on apigateway/src/test/java/nva/commons/apigateway/ApiGatewayHandlerTest.java
> +        assertThat(requestBody, is(notNullValue()));
if the handler is echoing the request, can you verify that you are receiving the request obejct?

2022-02-22 09:44 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/GatewayResponse.java
> +    public static <T> GatewayResponse<T> fromOutputStream(ByteArrayOutputStream outputStream, Class<T> className)
In the above comment, you can add @JacocoGenerated to deprecated methods

2022-02-22 10:55 UTC, axthosarouris submitted a review, later dismissed

2022-02-22 11:05 UTC, axthosarouris approved these changes

2022-02-22 11:07 UTC, merged