Np 9117 add nin to requestinfo
BIBSYSDEV/nva-commons pull request #374
Opened 2022-05-12 11:26 UTC by torarnet

2022-05-12 19:55 UTC, axthosarouris requested changes
Use only one claim `custom:nin` and the other one use it only as a JsonAlias when you are reading the Cognito userinfo data.

2022-05-12 19:55 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +    public String getPersonNinId() {
getPersonNin, not NinId

2022-05-12 19:55 UTC, axthosarouris commented on auth/src/main/java/no/unit/nva/auth/CognitoUserInfo.java
> +    @JsonProperty(PERSON_NIN_ID_CLAIM)
Use the @JsonAlias to avoid having two fields

2022-05-12 19:55 UTC, axthosarouris commented on nvatestutils/src/main/java/no/unit/nva/testutils/HandlerRequestBuilder.java
> +    public HandlerRequestBuilder<T> withPersonNinId(String personNinId) {
Here we start to leak cognito specific things to everywhere. We should have one method here, `withPersonNin`

2022-05-12 19:55 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +        return getRequestContextParameterOpt(PERSON_NIN_ID);
Since here we are only trying to inject a value, we do not have to have two ways to inject a value. Use the "custom:nin" claim only everywhere, except for CognitoInfo where you should add the alias as directed

2022-05-16 09:07 UTC, svenngjeto commented on auth/src/main/java/no/unit/nva/auth/CognitoUserInfo.java
> +    public static final String PERSON_NIN_CLAIM = "custom:nin";
NIN is the same wherever i comes from, shouldn't  "custom:nin" and  "custom:feideIdNin" be just one claim?

2022-05-16 09:55 UTC, axthosarouris commented on auth/src/main/java/no/unit/nva/auth/CognitoUserInfo.java
> +    public static final String PERSON_NIN_CLAIM = "custom:nin";
These information come from dataporten. They are different fields in dataporten and in Cognito we cannot map two input fields (Dataporten) to the same cognito field.

2022-05-18 07:14 UTC, axthosarouris approved these changes

2022-05-18 07:14 UTC, axthosarouris commented on auth/src/main/java/no/unit/nva/auth/CognitoUserInfo.java
> +    @JsonAlias({PERSON_NIN_CLAIM, PERSON_FEIDE_NIN_CLAIM})
You need to include only the "PERSON_FEIDE_NIN_CLAIM" in the alias.

2022-05-18 07:50 UTC, brinxmat approved these changes

2022-05-18 08:22 UTC, axthosarouris approved these changes

2022-05-18 08:25 UTC, merged