NP-13048 added support for reading plain-text secret as JSON
BIBSYSDEV/nva-commons pull request #392
Opened 2022-09-12 12:23 UTC by ketilaa

2022-09-13 11:15 UTC, brinxmat submitted a review, later dismissed

2022-09-13 12:02 UTC, ketilaa commented on nvatestutils/src/main/java/no/unit/nva/stubs/FakeSecretsManagerClient.java
> +        if (secrets.containsKey(secretName)) {
Tar gjerne innspill på om det går an å gjøre dette mer elegant.

2022-09-14 07:36 UTC, axthosarouris requested changes
Good job, Not sure about the necessity JSON parsing

2022-09-14 07:36 UTC, axthosarouris commented on nvatestutils/src/test/java/no/unit/nva/stubs/FakeSecretsManagerClientTest.java
> +    void shouldBeUsableWithSecretsReaderUsingPlainTextJson() {
since the secret in AWS is considered to be a plain text, then maybe it is better for the SecretsReader to return a String and the responibility to parse to JSON to be in the application (i.e. the code that is interested in the secret value).

example:
```
var secretString = secretsReader.fetchPlainTextSecret(secretName);
var json = parseJson(secretString)
```

2022-09-14 07:36 UTC, axthosarouris commented on secrets/src/test/java/nva/commons/secrets/SecretsReaderTest.java
> +    public void fetchJsonSecretReturnsDeserializedObjectCorrectly() {
it should not be the responsibilty of the secrets reader to parse the value of a plain text secret. What if the application chooses to use another type of serialization? we shouldn't need to change commons for that,

2022-09-14 08:33 UTC, ketilaa commented on nvatestutils/src/test/java/no/unit/nva/stubs/FakeSecretsManagerClientTest.java
> +    void shouldBeUsableWithSecretsReaderUsingPlainTextJson() {
Fixed

2022-09-14 08:33 UTC, ketilaa commented on secrets/src/test/java/nva/commons/secrets/SecretsReaderTest.java
> +    public void fetchJsonSecretReturnsDeserializedObjectCorrectly() {
Fixed

2022-09-14 10:33 UTC, axthosarouris approved these changes

2022-09-14 10:40 UTC, merged