Added ApiGatewayProxyHandler which extends ApiGatewayHandler but isnt…
BIBSYSDEV/nva-commons pull request #393
Opened 2022-09-15 08:53 UTC by sondrev

…ead of abstracting two different methods; one for body and one for http-status, it only abstracts one which needs to return both.

2022-09-15 11:39 UTC, axthosarouris requested changes

2022-09-15 11:39 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/ApiGatewayProxyHandler.java
> +        Pair<O, Integer> result = processProxyInput(input, requestInfo, context);
Lambda start up times are affected by the number of classes we are loading through dependencies. We should avoid depending on a whole module for a simple class. 
Using Pair is maybe a bit of an anti-pattern here because we always know what left and right is here and we should define them in a (ProxyResponse) class. That way we make our code more robust against wrong usage (e.g. someone mixing left with right). 
See https://github.com/BIBSYSDEV/nva-commons/pull/394 for a suggestion.

2022-09-15 11:49 UTC, sondrev commented on apigateway/src/main/java/nva/commons/apigateway/ApiGatewayProxyHandler.java
> +        Pair<O, Integer> result = processProxyInput(input, requestInfo, context);
Agreed, and thank you for providing a fix which I merged!

2022-09-16 07:33 UTC, axthosarouris approved these changes

2022-09-16 07:44 UTC, merged