Feide id request info
BIBSYSDEV/nva-commons pull request #395
Opened 2022-09-28 14:00 UTC by truhacevkir

2022-09-28 14:16 UTC, axthosarouris requested changes
At least one test is testing something else that what is claiming to test. No test for the case of the absence of the value.  
You should also allow the HandlerRequestBuilder to add the value so that we can use the value during testing.

2022-09-28 14:16 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +        return getQueryParameterOpt(parameter).orElseThrow(
reformat so that the method argument is on the same line as the method itself

2022-09-28 14:16 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +        return getRequestContextParameterOpt(jsonPointer).orElseThrow(
ditto

2022-09-28 14:16 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +        return extractFeideId().or(this::fetchFeideIdFromCognito).orElseThrow(UnauthorizedException::new);
extractFeideIdOffline

2022-09-28 14:16 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +    private Optional<? extends String> fetchFeideIdFromCognito() {
`Optional<String>`. The warnings of you IDE are your friends. Do not ignore them

2022-09-28 14:16 UTC, axthosarouris commented on apigateway/src/test/java/nva/commons/apigateway/RequestInfoTest.java
> +    }
These tests contain identical code but they test totally opposite scenarios.

2022-09-29 06:37 UTC, truhacevkir commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +        return getQueryParameterOpt(parameter).orElseThrow(
Fixed

2022-09-29 06:38 UTC, truhacevkir commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +        return getRequestContextParameterOpt(jsonPointer).orElseThrow(
fixed

2022-09-29 06:45 UTC, truhacevkir commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +        return extractFeideId().or(this::fetchFeideIdFromCognito).orElseThrow(UnauthorizedException::new);
fixed

2022-09-29 06:45 UTC, truhacevkir commented on apigateway/src/test/java/nva/commons/apigateway/RequestInfoTest.java
> +    }
fixed

2022-09-29 07:46 UTC, truhacevkir commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +    private Optional<? extends String> fetchFeideIdFromCognito() {
fixed

2022-09-29 09:32 UTC, axthosarouris requested changes

2022-09-29 09:32 UTC, axthosarouris commented on nvatestutils/src/test/java/no/unit/nva/testutils/HandlerRequestBuilderTest.java
> +        assertThat(requestInfo.getFeideId().get(),is(equalTo(expectedFeideId)));
orElseThrow

2022-09-29 09:32 UTC, axthosarouris commented on nvatestutils/src/test/java/no/unit/nva/testutils/HandlerRequestBuilderTest.java
> +    void buildReturnsOptionalWhenFeideIdNotSet() throws JsonProcessingException {
...returnsEmptyOptional....

2022-09-29 09:32 UTC, axthosarouris commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +                currentCustomer -> new AccessRightEntry(accessRight, currentCustomer))
This is probably due to auto-formatting but it reduces readability.
It is best if the argument of the function is on the same line as the funtion name. i.e.,
```
map(x->doSomething(x)) is eaiser to read than
map(
x-> doSomething(x))
```

Suggestion:
```
private boolean checkAuthorizationOffline(String accessRight) {
        return attempt(this::getCurrentCustomer)
                   .map(currentCustomer -> new AccessRightEntry(accessRight, currentCustomer))
                   .map(requiredAccessRight -> fetchAvailableAccessRights().anyMatch(requiredAccessRight::equals))
                   .orElse(fail -> handleAuthorizationFailure());
    }
```

2022-09-29 10:10 UTC, truhacevkir commented on nvatestutils/src/test/java/no/unit/nva/testutils/HandlerRequestBuilderTest.java
> +    void buildReturnsOptionalWhenFeideIdNotSet() throws JsonProcessingException {
fixed

2022-09-29 10:15 UTC, truhacevkir commented on nvatestutils/src/test/java/no/unit/nva/testutils/HandlerRequestBuilderTest.java
> +        assertThat(requestInfo.getFeideId().get(),is(equalTo(expectedFeideId)));
fixed

2022-09-29 10:15 UTC, truhacevkir commented on apigateway/src/main/java/nva/commons/apigateway/RequestInfo.java
> +                currentCustomer -> new AccessRightEntry(accessRight, currentCustomer))
fixed

2022-09-29 11:30 UTC, axthosarouris approved these changes

2022-09-29 11:59 UTC, merged