bugfix-doi-validator, fixed
BIBSYSDEV/nva-commons pull request #400
Opened 2022-10-20 15:07 UTC by anetteOlli

2022-10-20 15:08 UTC, anetteOlli commented on buildSrc/src/main/groovy/nvacommons.java-conventions.gradle
> +version = '1.25.13'
Det er her jeg bumper versjonen slik at det havner ut på mavencentral?

2022-10-20 15:11 UTC, anetteOlli commented on doi/src/main/java/nva/commons/doi/DoiValidator.java
> +        return urlMatcher.matches() && isUri(doi) || stringMatcher.matches();
var usikker på om jeg skulle kaste meg over regex'en eller bare sjekke kjapt om den teoretisk sett er en uri. Så jeg starter med latskapsprogrammering. urlMatcher er tydeligvis fornøyd så lenge det en eller annen plass inni strengen er en valid doi-url

2022-10-20 23:41 UTC, brinxmat approved these changes

2022-10-20 23:41 UTC, brinxmat commented on doi/src/main/java/nva/commons/doi/DoiValidator.java
> +        return urlMatcher.matches() && isUri(doi) || stringMatcher.matches();
Tror du gjør det riktige valg her — vi har noen problemer med testdata her da DOI-ene som produseres i DoiSuppliers er ikke riktige (linje 96 bør være noe a la: `String prefixSecondPart = Integer.toString(randomInteger(999999999));`).

Og regexen kunne vært, f.eks. `^https?://(?:dx\.)?doi\.org/10\.\d+/\S+$`

2022-10-20 23:41 UTC, brinxmat commented on doi/src/main/java/nva/commons/doi/DoiValidator.java
> +        return urlMatcher.matches() && isUri(doi) || stringMatcher.matches();
Denne ville tatt feilen du oppdaget.

2022-10-20 23:42 UTC, brinxmat requested changes

2022-10-20 23:42 UTC, brinxmat commented on doi/src/main/java/nva/commons/doi/DoiValidator.java
> +        return urlMatcher.matches() && isUri(doi) || stringMatcher.matches();
Hvis du ønsker kan jeg rette dette i en annen PR.

2022-10-21 06:56 UTC, anetteOlli commented on doi/src/main/java/nva/commons/doi/DoiValidator.java
> +        return urlMatcher.matches() && isUri(doi) || stringMatcher.matches();
Skal ikke prefix være et sted mellom 4 og 9 siffer?

https://support.datacite.org/docs/doi-basics
her foreslår de også en validator med spesifisert hvilke tegn som kan inngå i suffikset.

2022-10-21 07:02 UTC, anetteOlli commented on doi/src/test/java/nva/commons/doi/DoiValidatorTest.java
> +
fikset

2022-10-21 07:02 UTC, anetteOlli commented on doi/src/test/java/nva/commons/doi/DoiValidatorTest.java
> +    private static final String ATTACHEMENT = " 02872-6 ";
fikset

2022-10-21 07:02 UTC, anetteOlli commented on doi/src/test/java/nva/commons/doi/DoiValidatorTest.java
> +    @Test
fikset

2022-10-21 12:44 UTC, axthosarouris requested changes

2022-10-21 12:44 UTC, axthosarouris commented on buildSrc/src/main/groovy/nvacommons.java-conventions.gradle
> +version = '1.25.13'
the version is now outdated

2022-10-23 08:55 UTC, brinxmat commented on doi/src/main/java/nva/commons/doi/DoiValidator.java
> +        return urlMatcher.matches() && isUri(doi) || stringMatcher.matches();
Du har rett i forholdet til prefiks. Jeg lenket til Gilmartin-posten i Slack som refereres til i dokumentet du lenker til, anbefaler å lese den før vi bestemmer oss for noe i det hele tatt. 

```
    A Crossref [blog post](http://blog.crossref.org/2015/08/doi-regular-expressions.html) by Andrew 
    Gilmartin gives a good overview about the characters found in DOIs and suggests the following 
    regular expression to check for valid DOIs:

     /^10.\d{4,9}/[-._;()/:A-Z0-9]+$/i"
```

Fra mitt ståsted holder `^https?://(?:dx\.)?doi\.org/10\.\d{4,9}/\S+$` der` \S+` er viktig…

2022-10-23 08:56 UTC, brinxmat approved these changes

2022-10-31 11:59 UTC, anetteOlli commented on buildSrc/src/main/groovy/nvacommons.java-conventions.gradle
> +version = '1.25.13'
fikset

2022-10-31 11:59 UTC, anetteOlli commented on doi/src/main/java/nva/commons/doi/DoiValidator.java
> +        return urlMatcher.matches() && isUri(doi) || stringMatcher.matches();
fikset

2022-10-31 12:47 UTC, brinxmat approved these changes

2022-11-03 09:19 UTC, merged