added a secret-reader for JSON objects
BIBSYSDEV/nva-commons pull request #403
Opened 2022-10-27 12:18 UTC by sondrev

2022-10-27 12:24 UTC, axthosarouris submitted a review, later dismissed

2022-10-27 13:34 UTC, brinxmat requested changes

2022-10-27 13:34 UTC, brinxmat commented on secrets/src/test/java/nva/commons/secrets/SecretsReaderTest.java
> +    @Test
Kan du teste hva som skjer når hemmeligheten er en JSON array (ja, dette skjer)?

2022-10-27 13:34 UTC, brinxmat commented on secrets/src/test/java/nva/commons/secrets/SecretsReaderTest.java
> +        Credentials credentials = secretsReader.fetchClassSecret(JSON_SECRET_NAME, Credentials.class);
Bruk "var" overalt, vi kan også ta en vurdering på naming i testene — vi bør foretrekke BDD-style her.

2022-10-28 10:26 UTC, brinxmat approved these changes

2022-10-28 10:59 UTC, merged