fix: s3Driver lists files only of selected folder and not of similar folders
BIBSYSDEV/nva-commons pull request #414
Opened 2023-01-12 12:01 UTC by axthosarouris

Bug Description:

Currently
 Given that there are two folders "hello" and "hello-world" 
 When `S3Driver.listAllFiles(UnixPath.of("hello"))` is called 
 Then data from both "hello" and "hello-world" are returned

After fix:
 Given that there are two folders "hello" and "hello-world" 
 When `S3Driver.listAllFiles(UnixPath.of("hello"))` is called 
 Then data  ONLY FROM  "hello" are returned

2023-01-12 12:03 UTC, axthosarouris commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +    private static Stream<String> prependRoot(Stream<String> pathElements) {
moved due to auto-formatting

2023-01-12 12:03 UTC, axthosarouris commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +    private static Stream<String> extractAllPathElements(String[] path) {
moved due to auto-formatting

2023-01-12 12:03 UTC, axthosarouris commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +    private static Stream<String> splitInputElementsContainingPathDelimiter(Stream<String> pathElements) {
moved due to auto-formatting

2023-01-12 12:03 UTC, axthosarouris commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +    private static Stream<String> discardNullArrayElements(String[] path) {
moved due to auto-formatting

2023-01-12 12:03 UTC, axthosarouris commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +    private static Stream<String> addRootIfPresentInOriginalPath(Stream<String> pathElements, String[] path) {
moved due to auto-formatting

2023-01-12 12:03 UTC, axthosarouris commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +    private static boolean pathBeginsWithRoot(String[] path) {
moved due to auto-formatting

2023-01-12 12:03 UTC, axthosarouris commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +    private static boolean pathIsEmpty(List<String> path) {
moved due to auto-formatting

2023-01-12 12:05 UTC, axthosarouris commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +    public boolean startsWith(UnixPath ancestor) {
new method: see the tests

2023-01-12 12:05 UTC, axthosarouris commented on core/src/test/java/nva/commons/core/paths/UnixPathTest.java
> +    void shouldReturnStartsWithTrueWhenOnePathIsAncestorOfOther(){
tests for new method "startsWith"

2023-01-12 12:06 UTC, axthosarouris commented on nvatestutils/src/main/java/no/unit/nva/stubs/FakeS3Client.java
> +               || filePath.startsWith(parentFolder);
using the new method to avoid the described bug that comes from matching strings and not paths

2023-01-12 12:06 UTC, axthosarouris commented on s3/src/test/java/no/unit/nva/s3/S3DriverTest.java
> +    void shouldListFilesForFolder(String wantedFolder, String unwantedFolder) throws IOException {
rewrote test to test the bug case

2023-01-12 12:36 UTC, sondrev commented
@axthosarouris Is it correct that this bug only affected the Fake driver used in tests, and not any production code? I cant see you changing any code that is used from non-tests

2023-01-13 08:09 UTC, brinxmat requested changes

2023-01-13 08:09 UTC, brinxmat commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +import java.util.*;
Prefer qualified imports

2023-01-13 11:05 UTC, axthosarouris commented
> @axthosarouris Is it correct that this bug only affected the Fake driver used in tests, and not any production code? I cant see you changing any code that is used from non-tests

@sondrev  you are right. I think the functionality of the FakeS3Client has diverged . I will fix it.

2023-01-13 11:05 UTC, axthosarouris commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +import java.util.*;
Fixed

2023-01-13 11:06 UTC, axthosarouris commented
I am converting it to Draft to fix the issue that @sondrev  pointed out

2023-03-07 12:38 UTC, closed without merging