moving PagedSearchResult<T> to nva-commons
BIBSYSDEV/nva-commons pull request #418
Opened 2023-02-07 14:18 UTC by ketilaa

I am yet again to implement a search endpoint with pagination, and want to move it to nva-commons from nav-verified-funding-sources.

Current implementation has the following features:

- fixed query parameters `query` and `size` for pagination
- currently no explicit support for real searches in generation if `id` (self URI) as search term won't be included unless it is added to `baseUri`
- personally, I find it a bit confusing that we use name `size` for both the query parameter and in the response for the total size of the entire result set. `totalSize` is a better name in the response in my opinion.

I know this is a bit different from the way we do in cristin-service where `page` and `results` are used as query parameters.

2023-02-07 15:53 UTC, brinxmat commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +    private final int totalSize;
perhaps "total hits" since this is what is counted?

2023-02-07 15:53 UTC, brinxmat commented on buildSrc/src/main/groovy/nvacommons.java-conventions.gradle
> +version = '1.28.0'
Thinking about this, does this not belong in its own search-commons module?

2023-02-09 09:53 UTC, torarnet submitted a review, later dismissed

2023-03-22 07:43 UTC, monaullah commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +    private final int totalSize;
Done

2023-03-22 10:08 UTC, torarnet approved these changes

2023-03-23 10:52 UTC, brinxmat requested changes

2023-03-23 10:52 UTC, brinxmat commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +        URI previousResults = calculatePreviousResults(queryOffset, querySize, baseUri, queryParameters);
var

2023-03-23 10:52 UTC, brinxmat commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +    public PagedSearchResult(@JsonProperty(CONTEXT_FIELD_NAME) URI context,
A comment that is not directly actionable, but is worth thinking about: bizarrely, the context is always the same for this object. We have made it configurable because we don't know what this URI is, I guess. Is it unwise to fix this URI in this object because the object is "generic", or because we don't reliably serve the URI?

2023-03-23 10:52 UTC, brinxmat commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +                                            int noHits,
numberOfHits — I got confused by the naming

2023-03-23 10:52 UTC, brinxmat commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +        if ((queryOffset + noHits) < totalHits) {
Is it less than or equal to, perhaps?

2023-03-23 10:52 UTC, brinxmat commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +        if ((queryOffset + noHits) < totalHits) {
I'd probably test it

2023-03-23 11:44 UTC, monaullah commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +        URI previousResults = calculatePreviousResults(queryOffset, querySize, baseUri, queryParameters);
Done

2023-03-23 11:44 UTC, monaullah commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +                                            int noHits,
Agreed

2023-03-23 12:10 UTC, monaullah commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +    public PagedSearchResult(@JsonProperty(CONTEXT_FIELD_NAME) URI context,
Good point. Made context constant (https://bibsysdev.github.io/src/search/paginated-search-result.json), will define asap.

2023-03-29 11:54 UTC, brinxmat requested changes

2023-03-29 11:54 UTC, brinxmat commented on pagination/src/test/java/no/unit/nva/commons/pagination/PaginatedSearchResultTest.java
> +
Add a test for nonsense values:

```
    @ParameterizedTest
    @CsvSource({"10,0", "-1,10", "10,-1"})
    void shouldThrowOnNonsenseRequest(int offset, int size) {
        assertThrows(Exception.class, () -> PaginatedSearchResult.create(BASE_URI, offset, size, 50,
                                                                 Collections.emptyList(), Collections.emptyMap()));
    }
```

2023-03-29 11:54 UTC, brinxmat commented on pagination/src/test/java/no/unit/nva/commons/pagination/PaginatedSearchResultTest.java
> +
Interestingly, I'm not sure what the exception should be. The server should return something that is in the 4XX range, but there are a few candidates. 422 with a message would probably be best, but I have seen 400 (which is wrong for good reasons: the request _is_ valid syntactically) and 404 suggested. I think 422 _is_ better, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422, but it is also a bit uncommon.

2023-03-29 11:54 UTC, brinxmat commented on pagination/src/test/java/no/unit/nva/commons/pagination/PaginatedSearchResultTest.java
> +    @Test
Another option is to say that this is also an exception.

2023-03-29 11:54 UTC, brinxmat commented on pagination/src/main/java/no/unit/nva/commons/pagination/PaginatedSearchResult.java
> +    public PaginatedSearchResult(@JsonProperty(ID_FIELD_NAME) URI id,
Since we want to force use of the factory methods "create", hide the constructor.

2023-03-29 11:56 UTC, brinxmat commented on pagination/src/main/java/no/unit/nva/commons/pagination/PagedSearchResult.java
> +        if ((queryOffset + noHits) < totalHits) {
I tried to address my confusion — for some reason I was expecting a different order in the code. I am also good at maths (ahem) :D

2023-03-29 15:02 UTC, monaullah commented on pagination/src/test/java/no/unit/nva/commons/pagination/PaginatedSearchResultTest.java
> +
See https://github.com/BIBSYSDEV/nva-commons/pull/428

2023-03-30 11:33 UTC, brinxmat approved these changes

2023-03-30 11:37 UTC, merged