UnixPath - get second to last element
BIBSYSDEV/nva-commons pull request #433
Opened 2023-05-09 05:52 UTC by monaullah

2023-05-09 06:48 UTC, brinxmat requested changes

2023-05-09 06:48 UTC, brinxmat commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +    public String getSecondToLastPathElement() {
Probably just:

```
    public String getPathElementByIndex(int index) {
        return path.get(index);
    }
    
    public String getPathElementByIndexFromEnd(int index) {
      return path.get(path.size() - index);
   }
```

2023-05-09 06:48 UTC, brinxmat commented on core/src/main/java/nva/commons/core/paths/UnixPath.java
> +    public String getSecondToLastPathElement() {
Naming…yep, I know.

2023-05-09 09:18 UTC, brinxmat requested changes

2023-05-09 10:07 UTC, monaullah commented on core/src/test/java/nva/commons/core/paths/UnixPathTest.java
> +    }
Done, with an adjustment: `assertThat(unixPath.getPathElementByIndexFromEnd(value + 1), is(equalTo(expected)));`

2023-05-10 06:23 UTC, brinxmat approved these changes

2023-05-10 08:19 UTC, brinxmat approved these changes

2023-05-10 10:29 UTC, merged