firehose-client
BIBSYSDEV/nva-commons pull request #436
Opened 2023-05-15 12:19 UTC by axthosarouris

A Kinesis Firehose collects the records that are pushed to it and stores them in an S3 bucket.
  The important feature is that it collects multiple records in ZIP files and organizes the ZIP files by timestamp:
  s3://some-bucket/some-folder/2023/05/08/18/some-prefix-2023-05-08-18-01-17-lfksdjflskd-srdfsdef-sefsdf-sdfsd
  -sgdfsdfsdfs.gz

This a stub for Firehose client for testing

2023-05-15 15:46 UTC, brinxmat requested changes

2023-05-15 15:46 UTC, brinxmat commented on nvatestutils/src/test/java/no/unit/nva/stubs/FakeFirehoseClientTest.java
> +        PutRecordBatchRequest request = PutRecordBatchRequest.builder()
var

2023-05-16 07:36 UTC, anetteOlli submitted a review, later dismissed
Side note:
Det ser ut til at det har kommet på plass noe bibliotek for testing med aws resurser:
https://madhead.github.io/aws-junit5/asciidoc/

2023-05-18 07:24 UTC, axthosarouris commented
> Side note: Det ser ut til at det har kommet på plass noe bibliotek for testing med aws resurser: https://madhead.github.io/aws-junit5/asciidoc/

Nice! I think this is to be used in combination with localstack which could be very interesting. It is certainly worth a look and a better solution than the custom implemented testing clients

2023-05-19 17:36 UTC, brinxmat approved these changes

2023-05-19 18:21 UTC, merged