Support for (de)?serialization of optionals
BIBSYSDEV/nva-commons pull request #96
Opened 2020-09-07 10:31 UTC by norrs

Allow easy usage of optionals in APIs.

2020-09-07 15:26 UTC, axthosarouris commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +    public void jsonParserSerializedOptionalPresentAsT() throws JsonProcessingException {
jsonParserSerialize**s**OptionalPresentAsContainedValue?

2020-09-07 15:27 UTC, axthosarouris commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +        String sut = JsonUtils.objectMapper.writeValueAsString(new TestObjectForOptionals("foo"));
Avoid magic strings. Use constants such as SAMPLE_VALUE

2020-09-07 15:27 UTC, axthosarouris commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +        String sut = JsonUtils.objectMapper.writeValueAsString(new TestObjectForOptionals("foo"));
sut->actual

2020-09-07 15:52 UTC, axthosarouris commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +        String sut = JsonUtils.objectMapper.writeValueAsString(new TestObjectForOptionals("foo"));
Do not use magic strings.

2020-09-07 16:19 UTC, axthosarouris requested changes
I lack a bit of context in the PR. Where are we going to serialize Optionals? Can you give an example?

2020-09-07 16:19 UTC, axthosarouris commented on build.gradle
> +    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jdk8', version: jacksonVersion
:+1:

2020-09-07 16:19 UTC, axthosarouris commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +    @Test
There are many magic string and a lot of replication in the Test Classes. I have summarized all my comments in the following suggestion. You can find more detail comments below.

```suggestion
   public static final JsonNode EMPTY_VALUE = null;
    public static final String SAMPLE_VALUE = "foo";
    public static final JsonNode JSON_OBJECT_WITH_VALUE = sampleJsonObjectWithSomeValue();
    public static final JsonNode JSON_OBJECT_WITHOUT_VALUE = sampleJsonObjectWithoutValue();


 @Test
    public void jsonParserSerializesOptionalPresentAsContainedObject() {
        JsonNode actual = serialize(objectWithSomeValue());
        assertThat(actual, is(equalTo(JSON_OBJECT_WITH_VALUE)));
    }

    @Test
    public void jsonParserSerializesOptionalNotPresentAsNull() {
        JsonNode actual = serialize(objectWithoutValue());
        assertThat(actual, is(equalTo(JSON_OBJECT_WITHOUT_VALUE)));
    }

    @Test
    public void jsonParserDeserializesOptionalNotPresent() {
        TestObjectForOptionals actual = deserialize(JSON_OBJECT_WITHOUT_VALUE);
        assertThat(actual.getTest(), is(equalTo(Optional.empty())));
        assertThat(actual.getTest(), isEmpty());
    }

    @Test
    public void jsonParserDeserializesOptionalPresent() {
        TestObjectForOptionals sut = deserialize(JSON_OBJECT_WITH_VALUE);
        assertThat(sut.getTest(), isPresentAnd(containsString(SAMPLE_VALUE)));
    }

    private TestObjectForOptionals objectWithoutValue() {
        return new TestObjectForOptionals(null);
    }

    private TestObjectForOptionals deserialize(JsonNode jsonObjectWithoutValue) {
        return JsonUtils.objectMapper.convertValue(jsonObjectWithoutValue,
            TestObjectForOptionals.class);
    }

 

    private TestObjectForOptionals objectWithSomeValue() {
        return new TestObjectForOptionals(SAMPLE_VALUE);
    }

    private <T> JsonNode serialize(T objectWithNullValue) {
        return JsonUtils.objectMapper.convertValue(objectWithNullValue, JsonNode.class);
    }

    private static JsonNode sampleJsonObjectWithSomeValue() {
        return JsonUtils.objectMapper.createObjectNode().put(JSON_KEY, SAMPLE_VALUE);
    }

    private static JsonNode sampleJsonObjectWithoutValue() {
        return JsonUtils.objectMapper.createObjectNode().set(JSON_KEY, EMPTY_VALUE);
    }

    private static class TestObjectForOptionals {

        private final String test;

        @JsonCreator
        public TestObjectForOptionals(@JsonProperty(JSON_KEY) String test) {
            this.test = test;
        }

        public Optional<String> getTest() {
            return Optional.ofNullable(test);
        }
    }
```

2020-09-07 16:19 UTC, axthosarouris commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +        String sut = JsonUtils.objectMapper.writeValueAsString(new TestObjectForOptionals("foo"));
I think the system under testing is the library or the Json parser. Better if you called it actual?

2020-09-07 16:19 UTC, axthosarouris commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +    private static class TestObjectOptionalOfNullable {
The classes TestObjectForOptionalNullable and TestObjectOptionalOfEmpty are not necessary.

2020-09-08 10:05 UTC, norrs commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +    public void jsonParserSerializedOptionalPresentAsT() throws JsonProcessingException {
@axthosarouris : Accepted your nice refactoring, should solve this.

2020-09-08 10:05 UTC, norrs commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +        String sut = JsonUtils.objectMapper.writeValueAsString(new TestObjectForOptionals("foo"));
@axthosarouris : Accepted your nice refactoring, should solve this.

2020-09-08 10:05 UTC, norrs commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +        assertThat(sut, is(equalTo("{\n  \"test\" : \"foo\"\n}")));
@axthosarouris : Accepted your nice refactoring, should solve this.

2020-09-08 10:05 UTC, norrs commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +        String sut = JsonUtils.objectMapper.writeValueAsString(new TestObjectForOptionals(null));
@axthosarouris : Accepted your nice refactoring, should solve this.

2020-09-08 10:05 UTC, norrs commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +            return Optional.ofNullable(test);
@axthosarouris : Accepted your nice refactoring, should solve this.

2020-09-08 10:05 UTC, norrs commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +        String sut = JsonUtils.objectMapper.writeValueAsString(new TestObjectForOptionals("foo"));
@axthosarouris : Accepted your nice refactoring, should solve this.

2020-09-08 10:05 UTC, norrs commented on src/test/java/nva/commons/utils/JsonUtilsTest.java
> +    private static class TestObjectOptionalOfNullable {
@axthosarouris : Accepted your nice refactoring, should solve this.

2020-09-09 12:36 UTC, axthosarouris submitted a review, later dismissed

2020-09-10 07:32 UTC, axthosarouris approved these changes

2020-09-10 07:32 UTC, axthosarouris commented on src/main/java/nva/commons/utils/JsonUtils.java
> +            .setSerializationInclusion(Include.NON_NULL)
do you need both? I think Include.NON_ABSENT contains Include.NON_NULL

2020-09-10 14:42 UTC, norrs commented on src/main/java/nva/commons/utils/JsonUtils.java
> +            .setSerializationInclusion(Include.NON_NULL)
@axthosarouris : You are correct, tests are passing when removing it, so I have pushed updates again. :+1:

2020-09-10 20:39 UTC, axthosarouris approved these changes

2020-09-10 20:41 UTC, axthosarouris commented on src/main/java/nva/commons/utils/JsonUtils.java
> +            .setSerializationInclusion(Include.NON_NULL)
It is written in the javadoc :)

2020-09-11 16:52 UTC, merged